trigger:
  branches:
    include:
      - feature/big-data
  paths:
    include:
      - notebooks/*
      - synapse/*
      
pool:
  vmImage: 'ubuntu-latest'
	    
variables:
- group: 'big-data-integration-secrets'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'
  
- script: |
    pip install pyspark
  displayName: "Install PySpark"
  
- script: |
    python notebooks/process_data.py
  env:
    DATBRICKS_HOST: $(databricksWorkspaceUrl)
    DATABRICKS_TOKEN: $(databricksToken)
  displayName: 'Deploy Databricks Notebook'
  
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'azureSubscription'
    azurePowerShellVersion: 'LatestVersion'
    scriptType: 'FilePath'
    scriptPath: 'synapse/analyze_sales.sql'
    scriptArguments: '-WorkspaceName $(synapseWorkspaceName)'
  displayName: 'Run Synapse SQL Script'