trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/*

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'

- script: |
   python ./scripts/data_script.py > output.txt
  displayName: 'Run data_script.py'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'scripts/data_script.py'
    artifactName: 'pipeline-script'
  displayName: 'Publish data_script.py artifact'
