trigger:
  branches:
    include:
      - main
  paths:
    include:
      - scripts/*

pool:
  vmImage: 'windows-latest'

variables:
  version: '1.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'

- script: |
   python ./scripts/data_script.py > module_3_output.txt
  displayName: 'Run data_script.py'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'module_3_output.txt'
    artifactName: 'script-output'
  displayName: 'Publish data_script.py artifact'
