trigger:
  branches:
    include:
      - feature  # Replace with your actual feature branch name
  paths:
    include:
      - scripts/*
      - *.sql  # Added to capture changes to SQL files
      - *.sqlproj  # Added to capture changes to project file

pool:
  vmImage: 'windows-latest'

variables:
  version: '1.0'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'

- script: |
    python ./scripts/data_script.py > module_4_output.txt
  displayName: 'Run data_script.py'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.1.x'
  displayName: 'Install .NET Core SDK'

# Install SQL Server Data Tools (SSDT)
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sqlproj'
    feedsToUse: 'select'
  displayName: 'NuGet Restore'

- task: VSBuild@1
  inputs:
    solution: 'Database.sqlproj'
    msbuildArgs: '/p:Configuration=$(buildConfiguration) /p:OutDir="$(Build.ArtifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Build SQL Project'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'module_4_output.txt'
    artifactName: 'script-output'
  displayName: 'Publish data_script.py artifact'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)\Database.dacpac'
    artifactName: 'sql-dacpac'
  displayName: 'Publish .dacpac artifact'

# Optional: Add a step to deploy the DACPAC to a database
# - task: SqlDacpacDeploymentOnMachineGroup@0
#   inputs:
#     taskType: 'dacpac'
#     dacpacFile: '$(Build.ArtifactStagingDirectory)\Database.dacpac'
#     sqlFile: ''
#     inlineSql: ''
#     serverName: 'your-sqlserver.database.windows.net'
#     databaseName: 'datawarehouse'
#     sqlUsername: '$(SqlUsername)'
#     sqlPassword: '$(SqlPassword)'
#     additionalArguments: '/p:BlockOnPossibleDataLoss=False'
#   displayName: 'Deploy DACPAC to SQL Database'