trigger:
  branches:
    include:
      - feature/big-data
  paths:
    include:
      - notebooks/*
      - synapse/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'big-data-integration-secrets'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Setup Python'

- script: |
    pip install pyspark
  displayName: 'Install PySpark'

- script: |
    python notebooks/process_data.py
  env:
    DATABRICKS_HOST: $(databricksWorkspaceUrl)
    DATABRICKS_TOKEN: $(databricksToken)
  displayName: 'Deploy Databricks Notebook'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'azureSubscriptionName'  # <-- Fix: use your actual service connection name
    ScriptType: 'InlineScript'
    Inline: |
      Invoke-Sqlcmd -ServerInstance "$(synapseWorkspaceName).sql.azuresynapse.net" -Database master -InputFile "synapse/analyze_sales.sql"
    azurePowerShellVersion: 'LatestVersion'
  displayName: 'Run Synapse SQL Script'
