print("Starting my data journey!")
print("Version:", 1.7)
print("Publish pipeline artfifact to Artifact Feed!")
print("Push feature branch to Azure Repo, created pipeline artifact, pushed to Artifact Feed!")
print("Created .dacpac file through Azure DevOps pipeline!")